### ISSUE TITLE
L1 - Design Issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/water-brush#1]
## Google Fonts Latin Core & Plus coverage

- [x] Design all the glyphs required both in the [Latin Core](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/core_unique-glyphs.txt) + [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [x] Create all the comb marks as mentioned below
- [x] Leave only the compound glyphs (e.g. `adblgrave`) marked in dark grey as pending to be created using the components

----

## Diacritics

- [x] Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [x] Once the definitive design is ensured in the `comb` marks Legacy marks, delete the legacy marks and add them back so they are made using the `comb` marks as components.
- [x] Diacritics need to be balanced (in weight, size, contrast) and match the style of the typeface design.
- [x] Adjust the vertical position using glyphs app locked guidelines.
- [x] Ensure related marks are consistent between them, e.g. `caron` and `circumflex`
- [x] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD) On page 30 of [this document](http://theinsectsproject.eu/wp-content/uploads/2017/05/Insects-Project-2nd-edition_screen.pdf) you can find detailed info around the vertical Caron.
- [x] Leave a 0 sidebearings value for the marks

----
## Glyphs

- [x] The `ampersand` and `Eng` need to be consistent (in size and style) with the font. See [RUSerius](https://github.com/googlefonts/are-you-serious/issues/2#issuecomment-870693956) as reference
- [x] The German Double SS need to be fixed. This [article](https://www.lucasfonts.com/learn/1E9E) is a good reference
- [x] Currency symbols are related to the overall design and have balanced proportions
- [x] `ordfeminine` and `ordmasculine` as well as superior numbers are well proportioned and with a balanced stem thickness. [Issue of reference](https://github.com/googlefonts/cherish/issues/2#issuecomment-872268750)
- [x] `fractions` and `superior` numerals have a good proportion + weight. [Issue of reference](https://github.com/googlefonts/cherish/issues/2#issuecomment-872268750)
- [x] Check the ligatures are not wider than the original combination of letters. E.g. `fi`

----
## Spacing

- [x] Inspect the spacing and kerning of the font to ensure it is working properly and most common cases are covered. [Issue of reference](https://github.com/googlefonts/moondance/issues/1#issuecomment-940151753)
- [x] Terminal forms spacing should avoid crashes or collisions. [Issue of reference](https://github.com/googlefonts/comforter/issues/7)

**Comment by RobLeuschke** [comment]
This font is ready for review.

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke, 

`copyright`, `registered` and `trademark` symbols are sanserif instead of brush style.
I've just updated the source file in DropBox. Please use it to fix the glyphs.

Thanks
<img width="795" alt="Screen Shot 2022-03-24 at 22 13 49" src="https://user-images.githubusercontent.com/48698976/160049818-7fc51bc7-8ba5-43a3-8fda-2b3ba39fa6f6.png">

**Comment by RobLeuschke** [comment]
Hi Vivi,

I have replaced the glyphs with brush styles. I have to confess that I am
unsure of the size of the ® and TM symbols. I think of them as being
smaller at the end of words or images. The © I think of needing to be a
size consistent with the numerals. It is the ® that I am unsure about.
Should it also be small like the TM or should it be the same size as the
©?  If these are the appropriate sizes, then this is done, otherwise,
please advise.

Thanks,

Rob

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke,

Thanks for the quick response with this. 

> I think of them as being smaller at the end of words or images. The © I think of needing to be a size consistent with the numerals.

That would be the logic, although ® tends to be a bit taller than ™. I haven't inspected the new source file yet but I'm sharing here some pictures of examples.

**PT Seif**
<img width="460" alt="Screen Shot 2022-03-25 at 7 48 26" src="https://user-images.githubusercontent.com/48698976/160123608-8009046a-d057-4d20-97e5-9ef155c0f49c.png">


**Zapfino**
<img width="609" alt="Screen Shot 2022-03-25 at 7 44 33" src="https://user-images.githubusercontent.com/48698976/160123336-d76cff30-4bd8-4c4e-b215-3174e36634ea.png">

**Corinthia Regular** (yours :))
<img width="460" alt="Screen Shot 2022-03-25 at 7 45 13" src="https://user-images.githubusercontent.com/48698976/160123396-2e07e869-5baa-4e9f-a67a-ece205f113aa.png">

There are some cases where they use the same size as copyright for the registered mark, but out of its use it wouldn't say that is the ideal, it looks disproportionate.

**macOS System**
<img width="490" alt="Screen Shot 2022-03-25 at 7 43 48" src="https://user-images.githubusercontent.com/48698976/160124196-56fed3a7-46f1-41b2-9c0c-2c267244e8f5.png">

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke,

Please let me know if you perform any changes on the symbols after my previous comment. Thanks
